### ISSUE TITLE
Handle 404s better

### ISSUE THREAD

**Issue by rsnyman** [ibutsu/ibutsu-server#104]
When a user attempts to load an object that doesn't exist, the Ibutsu frontend has a "white page of death". We should handle these missing objects better with an "[object] not found" message.

For example:

https://server/run/this-run-does-not-exist

We could use the EmptyState component to show the error message: https://www.patternfly.org/v4/components/empty-state

**Comment by john-dupuy** [comment]
Fixed by #133
