### ISSUE TITLE
Use junitparser instead of homegrown parser

### ISSUE THREAD

**Issue by rsnyman** [ibutsu/ibutsu-server#117]
We should probably just use [junitparser](https://pypi.org/project/junitparser/) instead of our internal homegrown solution for parsing j/xUnit XML. This may help with issues like #92

**Comment by jjaquish** [comment]
Looking into this one

**Comment by rsnyman** [comment]
After a review, we realised that the junitparser doesn't support custom attributes like "xpassed" or "xfailed"
