### ISSUE TITLE
Support metadata in Import API

### ISSUE THREAD

**Issue by rsnyman** [ibutsu/ibutsu-server#135]
To make it easier to add metadata to a run created via the Import API, add a `metadata` field which can be applied to the run and the results.

- [x] Create `metadata` field in Import API spec
- [x] Add support for `metadata` field in Import controller
- [x] Apply metadata to run
- [x] Apply metadata to results

**Comment by jjaquish** [comment]
Going to take a look at this

**Comment by jjaquish** [comment]
This should do it: https://github.com/ibutsu/ibutsu-server/pull/194

**Comment by john-dupuy** [comment]
Closing as #194 has been merged, thanks @jjaquish! Next step will be to add support to the UI.
