### ISSUE TITLE
[GitHub Auth] See if we can workaround not being able to see user email 

### ISSUE THREAD

**Issue by john-dupuy** [ibutsu/ibutsu-server#260]
Users which have their email set to "private" in their preferences causes an auth request to return "null" for user.email.

This results in Ibutsu trying to create a user with a null email (which can't be done in the current schema). 

More info here: https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

**Comment by rsnyman** [comment]
Ah, so if the e-mail is null, we should perform a second request to the e-mails endpoint. We could do that.
