### ISSUE TITLE
Test history failures only show traceback

### ISSUE THREAD

**Issue by mshriver** [ibutsu/ibutsu-server#311]
The screenshot below shows how when looking at a test result's history, successful results have tabs for `Summary` and `Test Object`, but a failure result only shows the traceback.

The `Test Object` tab contains critical information for analyzing the test result history - like metadata.

I'd expect to see 3 tabs for test failures. 

![image](https://user-images.githubusercontent.com/21315076/158590857-64324a57-a952-4b35-8fe0-47565c7c043a.png)

**Comment by mshriver** [comment]
@john-dupuy you're just too cool. Thanks for the tip!!!

**Comment by rsnyman** [comment]
@mshriver I can roll this into some changes I'm making. Thanks for the input @john-dupuy !
