### ISSUE TITLE
Remove titles from pie and bar charts

### ISSUE THREAD

**Issue by JacobCallahan** [ibutsu/ibutsu-server#349]
Charts currently have a title attribute set, which serves little purpose. However, the title can render on top of the mouseover category label.

![Screenshot from 2022-05-23 13-01-58](https://user-images.githubusercontent.com/6618303/169871146-5d5cd391-825d-44cc-b001-904ad983ff0d.png)

This is a minor annoyance, but one that should be easily remedied by removing the following two lines:
https://github.com/ibutsu/ibutsu-server/blob/44a6d25d928806d1c7321893983418cdc1324017/frontend/src/widgets/resultaggregator.js#L128
and
https://github.com/ibutsu/ibutsu-server/blob/44a6d25d928806d1c7321893983418cdc1324017/frontend/src/widgets/resultaggregator.js#L152

**Comment by rsnyman** [comment]
There is a `legendData` attribute that we were generating data for, but not displaying. I'm not sure why, but maybe I can add that in, and it'll make the chart even nicer.
