### ISSUE TITLE
Unable to get an artifact by run id

### ISSUE THREAD

**Issue by quarckster** [ibutsu/ibutsu-server#370]
Ibutsu API returns 504 "Gateway timeout" if you try to get an artifact by run id.

Steps to reproduce:

1. Upload an archive with a run artifact
2. Perform GET request `/api/artifact?runId=<run id>`

Actual result:
The server returns 504

Expected result:
The server should return 200 and an array of artifacts

**Comment by rsnyman** [comment]
This was due to a missing index on the database. The index exists in the code, but it seems it was missed somewhere during a db upgrade.
