### ISSUE TITLE
[Enhancement] Improve usability of MetaFilter selection

### ISSUE THREAD

**Issue by jawatts** [ibutsu/ibutsu-server#387]
As a user, you have to fully type in the MetaData filter each time you want to filter. The list of filterable selections is a static list; allow for customization for a project, user, or dynamic  list population. 

![Screenshot from 2022-08-17 11-12-17](https://user-images.githubusercontent.com/31294478/185176452-e6873527-5f9b-4b96-91b2-4170bf377cb8.jpeg)

**Comment by rsnyman** [comment]
Actually, it is a dynamic list. Type in a field, and then click the "Create <field>" at the bottom of the list.

But getting a list of available metadata is something we've wanted to implement.

**Comment by Griffin-Sullivan** [comment]
In the PR I just mentioned this in I implemented the filter selection based off of selected project for MetaFilter, but I just realized that the screenshot here is for the normal results page that uses it's own filter. If you everyone likes my current implementation I could easily expand to the results page filter.
