### ISSUE TITLE
Test history is determined by test name instead of id

### ISSUE THREAD

**Issue by Griffin-Sullivan** [ibutsu/ibutsu-server#408]
Because the test history is filtered by test name you get all of the history for every test with that name. In robottelo, we have a couple instances where test names are reused like `test_positive_end_to_end` or `test_positive_create_with_name`. It would be better to filter by the uuid of the test or at least the test path, since the file.class.test_name should be unique.

**Comment by mshriver** [comment]
Difficult part is test UUID's aren't consistent - this is in a way a 'feature' of ibutsu, and why Polarion is such a PITA - having to manage test case instances and link them to tests in pytest.

I don't have a solution here, just a comment on why the situation is the way it is.

I think the solution might be on the client side, to inject an identifier into test case metadata that can then be used to consistently view test history (outside of ibutsu's history based on test name).
