### ISSUE TITLE
[Enhancement] Add dashboard widget for Test Run Heatmap

### ISSUE THREAD

**Issue by ntkathole** [ibutsu/ibutsu-server#411]
Currently ibutsu frontend have widget for Jenkins Pipeline Heatmap (A heatmap of test runs from a Jenkins pipeline). But there are certain scenarios where results are not uploaded via Jenkins or with Jenkins metadata. 

In such cases, we need similar widget to Jenkins Pipeline Heatmap that will collect test runs as per filters irrespective of jenkins job metadata. 

Example Scenario : Stage post deploy tests results which are not directly uploaded to ibutsu and fetched from aws bucket.

**Comment by rsnyman** [comment]
This should beg resolved with #428 so I'm going to close this issue.
