### ISSUE TITLE
Malformatted source CodeLink data which is missing a forward slash (/)

### ISSUE THREAD

**Issue by pavankrao** [ibutsu/ibutsu-server#422]
Example test run report: https://ibutsu.apps.ocp4.prod.psi.redhat.com/results/12b1b49f-ab56-4591-80f5-6341f28e6659
The Code Link data shows Code Link:
https://gitlab.cee.redhat.com/insights-qe/iqe-edge-plugin/-/tree/master/iqe_edgetests/rest/test_e2e.py#L58

There is a / missing between the two strings

**current format:**
iqe_edgetests 

and incorrect URL https://gitlab.cee.redhat.com/insights-qe/iqe-edge-plugin/-/tree/master/iqe_edgetests/rest/test_e2e.py#L58

**expected format:**
iqe_edge/tests 

and correct working URL https://gitlab.cee.redhat.com/insights-qe/iqe-edge-plugin/-/tree/master/iqe_edge/tests/rest/test_e2e.py#L58

**Comment by rsnyman** [comment]
As per our discussion, this is not an issue in Ibutsu server, so I'm going to close this issue.
