### ISSUE TITLE
TypeError opening project selection dropdown

### ISSUE THREAD

**Issue by mshriver** [ibutsu/ibutsu-server#46]
With a project is already selected, a TypeError occurs and the page goes blank when the project dropdown is clicked.

![image](https://user-images.githubusercontent.com/21315076/93594416-c9ce6480-f983-11ea-87e0-b6b5bdbe6202.png)

A refresh  reloads the page without error.

I can remove the selected project from the dropdown with the `X` in the dropdown, and then the dropdown behaves as expected, listing the available projects.

**Comment by rsnyman** [comment]
This was fixed in #69 and #72
